[project]
name = "app"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deepface>=0.0.95",
    "face-recognition>=1.3.0",
    "fastapi[standard]>=0.121.1",
    "opencv-python>=4.12.0.88",
    "pydantic-settings>=2.12.0",
    "tf-keras>=2.20.1",
    "ultralytics>=8.3.228",
]

[dependency-groups]
dev = [
    "pre-commit>=4.4.0",
]
